# Generated by Django 5.2.12 on 2026-05-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('photo', models.ImageField(blank=True, upload_to='instructors/photos/', verbose_name='photo')),
                ('car_photo', models.ImageField(blank=True, upload_to='instructors/cars/', verbose_name='car photo')),
                ('car_model', models.CharField(blank=True, max_length=100, verbose_name='car model')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price_per_hour', models.PositiveIntegerField(blank=True, null=True, verbose_name='price per hour')),
                ('certificate_photo', models.ImageField(blank=True, upload_to='instructors/certificates/', verbose_name='certificate photo')),
                ('vin_code', models.CharField(blank=True, max_length=17, verbose_name='VIN code')),
                ('tech_passport', models.ImageField(blank=True, upload_to='instructors/tech_passports/', verbose_name='technical passport')),
                ('is_official', models.BooleanField(default=False, verbose_name='official')),
                ('is_car_equipped', models.BooleanField(default=False, verbose_name='car equipped')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verification_note', models.TextField(blank=True, verbose_name='verification note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'instructors',
                'ordering': ['-created_at'],
            },
        ),
    ]
