# Generated by Django 5.2.12 on 2026-03-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
        migrations.AddField(
            model_name='user',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='paid until'),
        ),
    ]
