# Generated by Django 5.2.12 on 2026-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_meet_url',
            field=models.URLField(blank=True, help_text='Permanent Zoom/Meet link for teachers', verbose_name='default meeting link'),
        ),
    ]
