# Generated by Django 5.2.12 on 2026-05-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_default_meet_url'),
        ('users', '0004_user_license_categories'),
    ]

    operations = [
    ]
