# Generated by Django 5.2.12 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('student', 'Student'),
                    ('teacher', 'Teacher'),
                    ('instructor', 'Instructor'),
                    ('admin', 'Admin'),
                ],
                default='student',
                max_length=10,
                verbose_name='role',
            ),
        ),
    ]
