# Generated by Django 5.2.12 on 2026-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorychapter',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
