# Generated by Django 5.2.12 on 2026-03-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeimage',
            name='video_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
